Repository Nike-Inc/koheesio, pull requests merged in 2024-11, with the labels that each got.

#96 90-Bug-fix-file-encoding-box-integration
  src/koheesio/integrations/box.py
Labels: bug

#100 fix for DeltaMergeBuilder, when the instance doesn't check out
  src/koheesio/spark/writers/delta/batch.py
Labels: bug

#105 [FIX] Accidental duplication of logs
  src/koheesio/asyncio/__init__.py
  src/koheesio/integrations/box.py
  src/koheesio/integrations/snowflake/test_utils.py
  src/koheesio/integrations/spark/tableau/hyper.py
  src/koheesio/models/__init__.py
  src/koheesio/spark/readers/file_loader.py
  src/koheesio/spark/readers/rest_api.py
  src/koheesio/spark/transformations/__init__.py
  src/koheesio/spark/transformations/camel_to_snake.py
  src/koheesio/spark/transformations/date_time/interval.py
  src/koheesio/spark/transformations/lookup.py
  src/koheesio/spark/transformations/strings/change_case.py
  src/koheesio/spark/transformations/strings/split.py
  src/koheesio/spark/transformations/strings/trim.py
  src/koheesio/spark/transformations/uuid5.py
  src/koheesio/spark/writers/file_writer.py
  src/koheesio/steps/__init__.py
  tests/steps/test_steps.py
Labels: bug

#106 fix: adjust branch fetching
  .github/workflows/test.yml
Labels: blocked

#107 [FIX] broken import statements and updated hello-world.md
  README.md
  docs/reference/spark/transformations.md
  docs/tutorials/advanced-data-processing.md
  docs/tutorials/hello-world.md
  docs/tutorials/testing-koheesio-steps.md
  src/koheesio/spark/transformations/lookup.py
Labels: documentation

#117 [FEATURE] Populate account from url if not provided in SnowflakeBaseModel
  src/koheesio/integrations/snowflake/__init__.py
  tests/snowflake/test_snowflake.py
Labels: enhancement

#121 refactor: replace RunQuery with SnowflakeRunQueryPython
  src/koheesio/integrations/spark/snowflake.py
Labels: bug

#130 Fix/delta merge builder instance check for connect + util fix
  src/koheesio/spark/utils/connect.py
  src/koheesio/spark/writers/delta/batch.py
Labels: bug

#126 [FEATURE] Make Transformations callable
  pyproject.toml
  src/koheesio/spark/transformations/__init__.py
  tests/spark/transformations/test_transform.py
Labels: enhancement

#134 [BUG] small fix for Tableau Server path checking
  src/koheesio/integrations/spark/tableau/server.py
Labels: bug

#133 [FEATURE] DataBricksSecret for getting secrets from DataBricks scope
  docs/tutorials/getting-started.md
  src/koheesio/__about__.py
  src/koheesio/integrations/snowflake/__init__.py
  src/koheesio/integrations/spark/databricks/__init__.py
  src/koheesio/integrations/spark/databricks/secrets.py
  src/koheesio/integrations/spark/databricks/utils.py
  src/koheesio/integrations/spark/snowflake.py
  tests/spark/conftest.py
  tests/spark/integrations/databrikcs/test_secrets.py
  tests/spark/test_spark.py
Labels: enhancement

#138 [FIX] Remove mention of non-existent class type in docs
  src/koheesio/integrations/snowflake/__init__.py
Labels: bug, documentation

#140 [FIX] unused SparkSession being import from pyspark.sql in several tests
  tests/spark/integrations/dq/test_spark_expectations.py
  tests/spark/readers/test_hana.py
  tests/spark/readers/test_jdbc.py
  tests/spark/transformations/test_lookup.py
  tests/spark/transformations/test_row_number_dedup.py
Labels: bug
