Repository Nike-Inc/koheesio, pull requests merged in 2025-02, with the labels that each got.

#163 [FEATURE] Support for Delta table history
  pyproject.toml
  src/koheesio/spark/delta.py
  src/koheesio/spark/writers/delta/batch.py
  src/koheesio/utils/__init__.py
  src/koheesio/utils/date_time.py
  tests/spark/test_delta.py
  tests/utils/test_common_utils.py
  tests/utils/test_date_time_utils.py
Labels: enhancement

#164 [FEATURE] Introduce SecretStr and SecretBytes classes for enhanced secret handling
  pyproject.toml
  src/koheesio/models/__init__.py
  tests/models/test_models.py
  tests/sso/test_okta.py
Labels: enhancement

#168 [BUGFIX] Fix log duplication when using specific super call
  pyproject.toml
  src/koheesio/integrations/snowflake/__init__.py
  src/koheesio/spark/readers/hana.py
  src/koheesio/spark/readers/jdbc.py
  src/koheesio/spark/readers/teradata.py
  src/koheesio/spark/transformations/hash.py
  src/koheesio/steps/__init__.py
  tests/spark/integrations/snowflake/test_sync_task.py
  tests/spark/readers/test_jdbc.py
  tests/spark/transformations/test_hash.py
  tests/steps/test_http.py
  tests/steps/test_steps.py
Labels: bug

#170 [FEATURE] add authorization header to httpstep
  src/koheesio/steps/http.py
  tests/steps/test_http.py
Labels: bug, enhancement

#156 Bump version to 0.10.0
  src/koheesio/__about__.py
Labels: blocked

#172 feat - Also support reading a dict representing a json doc
  src/koheesio/spark/readers/memory.py
  tests/spark/readers/test_memory.py
Labels: enhancement
